name: api call
on:
  repository_dispatch:
    types: do-something
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: 'echo "Event text: ${{ github.event.client_payload.text }}"'
